### ISSUE TITLE
关于demo的问题

### ISSUE THREAD

**Issue by always-waiting** [apache/dubbo-getty#55]
看了demo的源码，也尝试运行了一下，有一个问题不是很明白。就是OnCron运行时如果发现超时了，会关闭session,但是为什么每次关闭之后，又会有一OnOpen事件发生？这个实现是在哪里完成的？

![截图_2020-12-15_15-40-00](https://user-images.githubusercontent.com/8566918/102185358-e67b2980-3eeb-11eb-9821-8f6574577f68.png)

请大神帮忙解答一下，谢谢

**Comment by always-waiting** [comment]
@wongoo 能否帮忙解析一下？谢谢！

**Comment by watermelo** [comment]
> 看了demo的源码，也尝试运行了一下，有一个问题不是很明白。就是OnCron运行时如果发现超时了，会关闭session,但是为什么每次关闭之后，又会有一OnOpen事件发生？这个实现是在哪里完成的？

client 会维持和 server 的连接数，当 OnCron 超时会关闭session然后检查连接数决定是否重连，调用链如下

```
func (c *client) reConnect()

session.stop() -> reConnect() -> connect()
```

**Comment by always-waiting** [comment]
@watermelo 谢谢！
