### ISSUE TITLE
Is the interface Session necessary?

### ISSUE THREAD

**Issue by Mulavar** [apache/dubbo-getty#70]
Session 接口目前由 getty 内部实现维护，且长期使用看下来仅有一种 session 机制实现， Session 接口起到的唯一作用是暴露作用域，可以通过直接将目前实现的结构体 session 首字母大写的方式替代。
以目前来看，提供一个 Session 接口好像仅仅是为了遵循面向接口编程的思想，但目前 getty 流程实际是和其实现 session 强绑定的，所以从精简代码设计的角度看是否可以考虑取消 Session 接口。

**Comment by AlexStocks** [comment]
时间已久，用户众多，想想修改后，别人的改造成本有多高？

**Comment by Mulavar** [comment]
我想了一下，其实做完改动，对用户来说只是Session从一个interface变成了一个struct，改动量应该是比较少的，getty1.4.3升1.4.4的时候时间轮那部分不兼容，需要用户修为为gost的，Session带来的改造应该跟这个差不多。

**Comment by AlexStocks** [comment]
有空翻翻 k8s 代码，很多 interface 的实现只有一个 struct，这并没有什么问题
