### ISSUE TITLE
Getty encounters broken pipeline issue

### ISSUE THREAD

**Issue by justxuewei** [apache/dubbo-getty#88]
![image](https://user-images.githubusercontent.com/13026316/147429940-5166dbad-3f19-4292-a8d6-047e61fd9215.png)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by Lvnszn** [comment]
观测到比较明显的现象是柔性这块的remain为0的时候，就会中断连接最终出现这种问题。
